### ISSUE TITLE
Map is not updated by itself, requires opening and closing the info drawer to reload

### ISSUE THREAD

**Issue by patrickmock** [cs340tabyu/Spring2017ImplementationTests#12]
When a user claims a route, other players do not see their name on the route in the map until they open and close the game info drawer.

**Comment by patrickmock** [comment]
Claimed routes do actually update if you click on a route in the map as well, but still require a user input as they don't update automatically

**Comment by ghost** [comment]
I fixed this. Map should update every time a player claims a route automatically.
