### ISSUE TITLE
Incorrect train cards are being used when claiming a route

### ISSUE THREAD

**Issue by dskou7** [cs340tabyu/Spring2017ImplementationTests#13]
Multiple instances / variations of this bug. 

-I wanted to claim a no-color (grey) length 2 route. I had 2 orange, 2 green, 2 yellow, 1 red, 1 rainbow. Instead of allowing me to choose what cards to use, it automatically chose my red and my rainbow. 

- selected a gray route, ended up with negative 2 rainbow cards instead of using existing train cards.

-tried to take a route of three pink trains, game used a yellow card and three locomotives (had 0 locomotives) (San Francisco to los angeles two routes) Ended up with -3 locomotives in hand

**Comment by adamriley1219** [comment]
Fixed it
