### ISSUE TITLE
No indication of who has longest route during the game.

### ISSUE THREAD

**Issue by adamriley1219** [cs340tabyu/Spring2017ImplementationTests#42]

**Comment by willhoney7** [comment]
Per passoff rubric, not necessary. Closing.

![image](https://user-images.githubusercontent.com/290380/27006005-939750b6-4de7-11e7-9bf5-9cc3257ebc07.png)

(https://students.cs.byu.edu/~cs340ta/spring2017/group_project/Phase3passoffrubric.pdf)
