### ISSUE TITLE
Train deck magically went from 6 cards remaining to 10 cards remaining.

### ISSUE THREAD

**Issue by tgrant13** [cs340tabyu/Spring2017ImplementationTests#43]
When trying to draw to the end of the deck it added 5 more cards one time.

**Comment by jnielson94** [comment]
This was likely from adding in any discarded cards once there were only 6 cards left in the deck to make it so that players can still draw from the deck. If there were no routes claimed (or no cards in the discard pile), let us know and we can look into it more.

**Comment by tgrant13** [comment]
Yeah we literally just looked into that. We got confused yesterday and
apparently missed that part of the rules. False alarm!
