### ISSUE TITLE
Doesn't handle zero destination cards left/incorrect number showing

### ISSUE THREAD

**Issue by patrickmock** [cs340tabyu/Spring2017ImplementationTests#48]
1. Started game with 2 players, each selected 2 initial destination cards.
2. Took turns doing nothing else but each taking 3 destination cards from the deck, and keeping all.
3. Eventually took all cards from the deck.
4. Tried to take more cards from the deck, 3 routes selections came up (like the player drew new cards) but they are all routes the player already has.
5. Same thing happens for other players, shows 3 routes they currently have.
6. One player's game info shows 3 remaining destination cards, with 11 cards on one player and 14 on the other (doesn't equal 30)
7. Other player's game info shows 0 remaining destination cards, with 16 cards on one player and 14 on the other (correctly reflects the destinations shown in their list of active destinations)

**Comment by ghost** [comment]
Matt fixed this. Good job!
