### ISSUE TITLE
Issues

### ISSUE THREAD

**Issue by tscheney** [cs340tabyu/Spring2017ImplementationTests#49]
I didn't want to log these all as separate issues, but here is what I've found so far:
The Routes claimed number in the status dialog doesn't update, and neither do the points.
Upon log out and log in you can re-select destination cards, including keeping only one.
The number of destination cards number in the status doesn't update when you draw. It does update if you log out and log back in and re-select cards.
You can draw as many face up cards as you want if you just keep clicking.
Minimizing the game makes you log out.
I wasn't able to draw as the second player the first time.
Sometimes the only way to end your turn is to send a chat.

**Comment by aaronfjerstad** [comment]
In the process of fixing those.
Note that our "logging in" process is actually connecting to a server authentication that doesn't disappear when you "log out". There are a couple problems with the process we are addressing.
