### ISSUE TITLE
When you click the Leave Game button, the app crashes, but when you log back in you aren't in the game anymore.

### ISSUE THREAD

**Issue by jnielson94** [cs340tabyu/Spring2017ImplementationTests#55]
Steps to reproduce:

1. Login
2. Create a Game
3. Click Leave Game
4. Reopen the app and login/register again
5. Verify that the number of players in the previously created game is 0 (or 1 less that there was if you have another player in that game).

**Comment by scwood** [comment]
Fixed by just removing the leave game button (not required)
