### ISSUE TITLE
You can register without specifying an ip address and port, and it looks like it works... until you try to create a game.

### ISSUE THREAD

**Issue by jnielson94** [cs340tabyu/Spring2017ImplementationTests#56]
Steps to Reproduce:
1. Register, but don't include an ip address/port number as shown: 
![screen shot 2017-06-09 at 22 08 14](https://user-images.githubusercontent.com/13559161/26999846-81e24ac4-4d60-11e7-916c-588e3aaf15b2.png)
2. Create a game
3. Have someone else login using a valid ip address and port for the server
4. See something like this:
![screen shot 2017-06-09 at 22 08 54](https://user-images.githubusercontent.com/13559161/26999849-9282b6f2-4d60-11e7-815d-b418bbd6f441.png)

**Comment by scwood** [comment]
Fixed
