### ISSUE TITLE
Startup Command doesn't work on linux

### ISSUE THREAD

**Issue by omginbd** [cs340tabyu/Spring2017ImplementationTests#9]
I can't run the server to look for other bugs.

`java -cp server.jar;lib/*;. com.cs340.team6.tickettoride.Communication.ServerCommunicator 8000`

Violates some syntax, and this just shows the java help page on linux.

**Comment by omginbd** [comment]
As an update, putting the classpath in quotes gets past the syntax error, but the specified class can't be found `java -cp "server.jar;lib/*;." com.cs340.team6.tickettoride.Communication.ServerCommunicator 8000`
 results in: 
`Error: Could not find or load main class com.cs340.team6.tickettoride.Communication.ServerCommunicator`

**Comment by ghost** [comment]
I'm writing this not knowing if this will actually fix your problem, but I'm pretty sure that the syntax issue is with the semi colons. The ';' is for windows. From what I've read, those can be replaced with ':' while running on linux. I don't have access to linux though, so I haven't been able to test this. So maybe:

java -cp server.jar:lib/*:. com.cs340.team6.tickettoride.Communication.ServerCommunicator 8000

would work.
